# Eat Safe, Love

## Notebook Set Up

In [53]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint

In [54]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [55]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [56]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [57]:
# assign the collection to a variable
establishments=db['establishments']
print(db.list_collection_names())

['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [58]:
#Create query to find establishments with hygiene score of 20
query = {"scores.Hygiene": 20}
print("Number of documents in result:", establishments.count_documents(query))

#print the first result to indicate structure
result = establishments.find()
pprint(result[0])

Number of documents in result: 41
{'AddressLine1': 'East Cliff Pavilion',
 'AddressLine2': 'Wear Bay Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'BusinessName': 'The Pavilion',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'ChangesByServerID': 0,
 'Distance': 4591.765489457773,
 'FHRSID': 1043695,
 'LocalAuthorityBusinessID': 'PI/000073616',
 'LocalAuthorityCode': '188',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'CT19 6BL',
 'RatingDate': '2018-04-04T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('646bfa7298a5457bc1c3437f'),
 'geocode': {'latitude': Decimal128('51.083812'),
             'longitude': Decimal128('1.195625')},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1043695',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}

In [59]:
# Query condition to match establishments with hygiene score of 20
query = {"scores.Hygiene": 20}

# Find establishments that match the query
matching_establishments = establishments.find(query)

# Iterate over the matching establishments and print their details
for establishment in matching_establishments:
    print("Business Name:", establishment["BusinessName"])
    print("Address:", establishment["AddressLine1"])
    print("City:", establishment["AddressLine3"])
    print("Postcode:", establishment["PostCode"])
    print("Hygiene Score:", establishment["scores"]["Hygiene"])
    print("-------------------")

Business Name: The Chase Rest Home
Address: 5-6 Southfields Road
City: East Sussex
Postcode: BN21 1BU
Hygiene Score: 20
-------------------
Business Name: Brenalwood
Address: Hall Lane
City: Essex
Postcode: CO14 8HN
Hygiene Score: 20
-------------------
Business Name: Melrose Hotel
Address: 53 Marine Parade East
City: Essex
Postcode: CO15 6AD
Hygiene Score: 20
-------------------
Business Name: Seaford Pizza
Address: 4 High Street
City: East Sussex
Postcode: BN25 1PG
Hygiene Score: 20
-------------------
Business Name: Golden Palace
Address: 5 South Street
City: East Sussex
Postcode: BN25 1HP
Hygiene Score: 20
-------------------
Business Name: Ashby's Butchers
Address: 777 Southchurch Road
City: Essex
Postcode: SS1 2PP
Hygiene Score: 20
-------------------
Business Name: South Sea Express Cuisine
Address: 33 Alexandra Street
City: Essex
Postcode: SS1 1BW
Hygiene Score: 20
-------------------
Business Name: Golden Palace
Address: 7 London Road
City: Essex
Postcode: SS6 9HN
Hygiene Score: 20
-------------------
Business Name: The Tulip Tree
Address: 3 The Village
City: KENT
Postcode: TN8 7AH
Hygiene Score: 20
-------------------
Business Name: F & S
Address:
City: Basildon
Postcode: SS14 1EU
Hygiene Score: 20
-------------------
Business Name: Longhouse
Address: 17 London Road
City: KENT
Postcode: TN13 2BU
Hygiene Score: 20
-------------------
Business Name: Westview Playgroup Based At Downsview Comm Primary
Address: Downsview Community Primary School
City: Swanley
Postcode: BR8 8AU
Hygiene Score: 20
-------------------
Business Name: Whatever The Weather Coffee
Address: EMR Erith
City: Erith
Postcode: DA8 2AD
Hygiene Score: 20
-------------------
Business Name: Kings Restaurant (Oriental)
Address: 43 Kings Road
City: Essex
Postcode: CM14 4DJ
Hygiene Score: 20
-------------------
Business Name: Xich Lo
Address: 24 Station Lane
City:
Postcode: RM12 6NJ
Hygiene Score: 20
-------------------
Business Name: Asian Supermarket Ltd: T/A Best Food Wine Ltd
Address: 2 - 6 Basildon Road
City: Abbey Wood
Postcode:
Hygiene Score: 20
-------------------
Business Name: Londis
Address: 5 - 7 Cranley Parade
City: Mottingham
Postcode: SE9 4DZ
Hygiene Score: 20
-------------------
Business Name: Costcutter
Address: 2 The Slade
City: Plumstead
Postcode: SE18 2NB
Hygiene Score: 20
-------------------
Business Name: La Simon Ltd
Address:
City:
Postcode: RM8 2AQ
Hygiene Score: 20
-------------------
Business Name: Caribiscus Ltd
Address:
City:
Postcode: IG11 8TB
Hygiene Score: 20
-------------------
Business Name: Kennedy Fried Chicken
Address:
City:
Postcode: IG11 8EA
Hygiene Score: 20
-------------------
Business Name: Gah Shing
Address: 5 High Street South
City: London
Postcode: E6 6EN
Hygiene Score: 20
-------------------
Business Name: A1 News & Wine
Address:
City:
Postcode: IG1 2RZ
Hygiene Score: 20
-------------------
Business Name: Cakes & Bakes
Address:
City:
Postcode: IG1 2LD
Hygiene Score: 20
-------------------
Business Name: Sahajanand Catering Limited
Address:
City:
Postcode: IG1 4BL
Hygiene Score: 20
-------------------
Business Name: Sisko Cafe
Address: 151 - 153 Barking Road
City: London
Postcode: E6 1LD
Hygiene Score: 20
-------------------
Business Name: Magazin Romanesc Diana
Address: 221 High Street North
City: London
Postcode: E6 1JG
Hygiene Score: 20
-------------------
Business Name: Bali Maamalas
Address: 241B High Street North
City: London
Postcode: E12 6SJ
Hygiene Score: 20
-------------------
Business Name: Angels Bakery
Address: 333 Barking Road
City: London
Postcode: E13 8EE
Hygiene Score: 20
-------------------
Business Name: Nikkis Place Restaurant
Address: 282 Barking Road
City: London
Postcode: E13 8HR
Hygiene Score: 20
-------------------
Business Name: Chicago 30
Address: 369 Katherine Road
City: London
Postcode: E7 8LT
Hygiene Score: 20
-------------------
Business Name: Samui Thai Restaurant
Address: The Kinema
City: Dunmow
Postcode: CM6 1HB
Hygiene Score: 20
-------------------
Business Name: Pakhtoonkhwa Restaurant
Address: 76 Green Street
City: London
Postcode: E7 8JG
Hygiene Score: 20
-------------------
Business Name: New Happy Garden
Address: 23 Stortford Road
City:
Postcode: CM6 1DA
Hygiene Score: 20
-------------------
Business Name: Mummy Yum
Address: 34 West Ham Lane
City: London
Postcode: E15 4SA
Hygiene Score: 20
-------------------
Business Name: Gospodina
Address:
City:
Postcode: E11 4JT
Hygiene Score: 20
-------------------
Business Name: Leo's Bar & Grill
Address:
City:
Postcode: E11 1HG
Hygiene Score: 20
-------------------
Business Name: Royal Ribs
Address:
City:
Postcode: E4 6LQ
Hygiene Score: 20
-------------------
Business Name: Great Hallingbury Manor Hotel
Address: Great Hallingbury Manor
City: Great Hallingbury
Postcode: CM22 7TJ
Hygiene Score: 20
-------------------
Business Name: The Dog And Duck
Address: 58 Lower Street
City: Essex
Postcode: CM24 8LR
Hygiene Score: 20
-------------------
Business Name: Oriental Cottage
Address: 1 Mercers Row
City: Essex
Postcode: CB10 1HD
Hygiene Score: 20
-------------------

In [60]:
import pandas as pd

# Projection to include only specific fields in the result
projection = {"BusinessName": 1, "AddressLine1": 1, "AddressLine3": 1, "PostCode": 1, "scores.Hygiene": 1}

# Find establishments that match the query and projection
matching_establishments = establishments.find(query, projection)

# Convert the query result to a DataFrame
df = pd.DataFrame(matching_establishments)

# Display the number of rows in the DataFrame
num_rows = df.shape[0]
print('There are',num_rows,'rows in the data frame.')

# Display the first 10 rows of the DataFrame
df.head(10)

There are 41 rows in the data frame.

,_id,BusinessName,AddressLine1,AddressLine3,PostCode,scores
0,646bfa7498a5457bc1c35eb1,The Chase Rest Home,5-6 Southfields Road,East Sussex,BN21 1BU,{'Hygiene': 20}
1,646bfa7498a5457bc1c36232,Brenalwood,Hall Lane,Essex,CO14 8HN,{'Hygiene': 20}
2,646bfa7598a5457bc1c3653c,Melrose Hotel,53 Marine Parade East,Essex,CO15 6AD,{'Hygiene': 20}
3,646bfa7598a5457bc1c3672a,Seaford Pizza,4 High Street,East Sussex,BN25 1PG,{'Hygiene': 20}
4,646bfa7598a5457bc1c36739,Golden Palace,5 South Street,East Sussex,BN25 1HP,{'Hygiene': 20}
5,646bfa7598a5457bc1c370d8,Ashby's Butchers,777 Southchurch Road,Essex,SS1 2PP,{'Hygiene': 20}
6,646bfa7598a5457bc1c372f9,South Sea Express Cuisine,33 Alexandra Street,Essex,SS1 1BW,{'Hygiene': 20}
7,646bfa7798a5457bc1c38824,Golden Palace,7 London Road,Essex,SS6 9HN,{'Hygiene': 20}
8,646bfa7898a5457bc1c38c68,The Tulip Tree,3 The Village,KENT,TN8 7AH,{'Hygiene': 20}
9,646bfa7998a5457bc1c3947a,F & S,,Basildon,SS14 1EU,{'Hygiene': 20}

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [61]:
#query to find establishments in London with RatingValue greater than or equal to 4 
query2 = {'LocalAuthorityName': {'$regex': "London"},
         'RatingValue': {'$gte': '4'}
         }
#count documents in result
count_docs= establishments.count_documents(query2)
print (f"There are {count_docs} establishments in London with a Rating Value greater than or equal to 4.")

#display documents in result using pretty print
pprint ( establishments.find_one(query2))

There are 34 establishments in London with a Rating Value greater than or equal to 4.
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': '4',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('646bfa7698a5457bc1c378cc'),
 'geocode': {'latitude': Decimal128('51.369321'),
             'longitude': Decimal128('0.508551')},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [62]:
query2 = {'LocalAuthorityName': {'$regex': "London"},
         'RatingValue': {'$gte': '4'}
         }
# Find establishments that match the query
matching_establishments_2 = establishments.find(query2)

# Iterate over the matching establishments and print their details
for establishment in matching_establishments_2:
    print("Business Name:", establishment["BusinessName"])
    print("Address:", establishment["AddressLine1"])
    print("Local Authority:", establishment["LocalAuthorityName"])
    print("Postcode:", establishment["PostCode"])
    print("Rating:", establishment["RatingValue"])
    print("-------------------")

# Projection to include only specific fields in the result
projection2 = {"BusinessName": 1, "AddressLine1": 1, "AddressLine3": 1, "PostCode": 1, "RatingValue": 1}

Business Name: Charlie's
Address: Oak Apple Farm Building 103 Sheernes Docks
Local Authority: City of London Corporation
Postcode: ME12
Rating: 4
-------------------
Business Name: Mv City Cruises Erasmus
Address: Cherry Garden Pier
Local Authority: City of London Corporation
Postcode: TN4 8HR
Rating: 5
-------------------
Business Name: Benfleet Motor Yacht Club
Address: Ferry Road
Local Authority: City of London Corporation
Postcode: SS7 1NF
Rating: 4
-------------------
Business Name: Coombs Catering t/a The Lock and Key
Address: Leslie Ford House
Local Authority: City of London Corporation
Postcode: RM18 7EH
Rating: 5
-------------------
Business Name: Tilbury Seafarers Centre
Address: Tenants Row Tilbury Docks
Local Authority: City of London Corporation
Postcode: RM18 7EH
Rating: 5
-------------------
Business Name: Mv Valulla
Address: Reeds River Cruises LtdKings ReachRiver ThamesSouthwark
Local Authority: City of London Corporation
Postcode: RM15 5QY
Rating: 5
-------------------
Business Name: Froottree
Address: Tereza Joanne King George V Lock
Local Authority: City of London Corporation
Postcode: E16 2NJ
Rating: AwaitingInspection
-------------------
Business Name: Tereza Joanne
Address: Funcraft UK Ltd King George V Dock Woolwich Manor Way
Local Authority: City of London Corporation
Postcode: E16 2NJ
Rating: 5
-------------------
Business Name: Brick Lane Brews
Address: Air side London City Airport
Local Authority: City of London Corporation
Postcode: E16 2PX
Rating: 4
-------------------
Business Name: The Nuance Group (UK) Limited
Address: Duty Free Shop Passenger Terminal
Local Authority: City of London Corporation
Postcode: E16 2PX
Rating: 5
-------------------
Business Name: WH Smith
Address: London City Airport
Local Authority: City of London Corporation
Postcode: E16 2PX
Rating: 5
-------------------
Business Name: City Bar & Grill
Address: London City Airport (Airside)
Local Authority: City of London Corporation
Postcode: E16 2PX
Rating: 5
-------------------
Business Name: Jet Centre
Address: London City Airport
Local Authority: City of London Corporation
Postcode: E16 2PJ
Rating: 5
-------------------
Business Name: Caffè Nero
Address: London City Airport Airside Departure Lounge
Local Authority: City of London Corporation
Postcode: E16 2PJ
Rating: 5
-------------------
Business Name: Mv Sunborn Yacht Hotel
Address: Western Gateway
Local Authority: City of London Corporation
Postcode: E16 1XL
Rating: 5
-------------------
Business Name: Good Hotel London
Address: Western Gateway Royal Victoria Dock
Local Authority: City of London Corporation
Postcode: E16 1FA
Rating: 5
-------------------
Business Name: La Nonna lina
Address: Dock Road
Local Authority: City of London Corporation
Postcode: E16 1AG
Rating: 4
-------------------
Business Name: Wake Up Docklands Limited
Address: Western Beach Royal Victoria Docks
Local Authority: City of London Corporation
Postcode: E16 1AG
Rating: 5
-------------------
Business Name: MV Venus Clipper
Address: Trinity Buoy Wharf
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: MV Typhoon clipper
Address: Thames Clippers Unit 12 The Riverside Building
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: MV Moon clipper
Address: Thames Clippers 3rd flr Clippers House
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: MV Jupiter clipper
Address: Thames Clippers Unit 12 The Riverside Building
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: MV Monsoon clipper
Address: Thames Clippers Unit 12 The Riverside Building
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: MV Meteor clipper
Address: Thames Clippers Unit 12 The Riverside Building
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: MV Tornado clipper
Address: Thames Clippers Unit 12 The Riverside Building
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: MV Mercury clipper
Address: Thames Clippers 3rd flr Clippers House
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: MV Cyclone clipper
Address: Thames Clippers Unit 12 The Riverside Building
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: MV Hurricane clipper
Address: Thames Clippers Unit 12 The Riverside Building
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: MV Neptune clipper
Address: Thames Clippers Unit 12 The Riverside Building
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: MV Galaxy clipper
Address: Thames Clippers Unit 12 The Riverside Building
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: MV Sun clipper
Address: Thames Clippers 3rd flr Clippers House
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: Mv Storm Clipper
Address: Thames Clippers Unit 12 The Riverside Building
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: MV Aurora clipper
Address: Thames Clippers Unit 12 The Riverside Building
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------
Business Name: Canary Wharf 1V
Address: Trinity Buoy Wharf
Local Authority: City of London Corporation
Postcode: E14 0JY
Rating: 5
-------------------

In [63]:
import pandas as pd

# Projection to include only specific fields in the result
projection2 = {"BusinessName": 1, "AddressLine1": 1, "AddressLine3": 1, "PostCode": 1, "RatingValue": 1}

# Find establishments that match the query and projection
matching_establishments_2 = establishments.find(query2)

# Convert the query result to a DataFrame
df2 = pd.DataFrame(matching_establishments_2)

# Display the number of rows in the DataFrame
num_rows2 = df2.shape[0]
print('There are',num_rows2,'rows in the data frame.')

# Display the first 10 rows of the DataFrame
df2.head(10)

There are 34 rows in the data frame.

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,646bfa7698a5457bc1c378cc,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...",FHRS,"{'longitude': 0.508551, 'latitude': 51.369321}",,4627.439468,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,646bfa7698a5457bc1c37bf2,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.249255999922752, 'latitude': 5...",,4627.873179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
2,646bfa7798a5457bc1c3873f,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.561954, 'latitude': 51.543831}",,4631.968418,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
3,646bfa7998a5457bc1c3953f,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.346336990594864, 'latitude': 5...",,4636.846754,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
4,646bfa7998a5457bc1c39540,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.346325, 'latitude': 51.464078}",,4636.847650,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
5,646bfa7998a5457bc1c39c48,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.287555, 'latitude': 51.504071}",,4640.460834,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
6,646bfa7c98a5457bc1c3bd52,1252616,0,PI/000035653,Froottree,Other catering premises,7841,Tereza Joanne King George V Lock,Woolwich Manor Way London,Charlton,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': None, 'Structural': None, 'Confide...",FHRS,"{'longitude': 0.0693250000476837, 'latitude': ...",,4648.300000,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
7,646bfa7c98a5457bc1c3bd56,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.069286, 'latitude': 51.501121}",,4648.301822,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,646bfa7d98a5457bc1c3c11d,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.048006, 'latitude': 51.503733}",,4649.173485,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,646bfa7d98a5457bc1c3c137,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.047966, 'latitude': 51.504112}",,4649.188826,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
10,646bfa7d98a5457bc1c3c138,294606,0,PI/000016185,WH Smith,Retailers - other,4613,London City Airport,Silvertown London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0479655750095844, 'latitude': ...",,4649.188850,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 3. What are the top 5 establishments with a `RatingValue` rating value of '5', sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [64]:
#find latitude and longitude of Penang Flavours
pprint(establishments.find_one({'BusinessName': 'Penang Flavours'}, {'geocode.latitude','geocode.longitude'}))

{'_id': ObjectId('646bfe8ae015039ce8facc03'),
 'geocode': {'latitude': Decimal128('51.49014200'),
             'longitude': Decimal128('0.08384000')}}

In [65]:
#set latitude and longitude coordinates for Penang flavours
degree_search = 0.01
latitude = 51.49014200
longitude = 0.08384000
#create query using parameters - latitude, lonitude and rating value of 5
query3 = {'RatingValue': '5',
         'geocode.latitude':{'$lte':(latitude+degree_search),'$gte':(latitude-degree_search)},
          'geocode.longitude':{'$lte':(longitude+degree_search),'$gte':(longitude-degree_search)}
         }
#sort results by lowest to highest hygiene scores
sort = [('scores.Hygiene',1)]

#sort and limit results to 5
result = establishments.find(query3).sort(sort).limit(5)

#count the number of documents in the resulting query
count_doc= establishments.count_documents(query3)
print (f"There are {count_doc} establishments in London with a Rating Value of greater or equal to 5.")

#pretty print the first result from the query
pprint(result[0])

There are 87 establishments in London with a Rating Value of greater or equal to 5.
{'AddressLine1': '144 - 146 Plumstead High Street',
 'AddressLine2': '',
 'AddressLine3': 'Plumstead',
 'AddressLine4': 'Greenwich',
 'BusinessName': 'Iceland',
 'BusinessType': 'Retailers - supermarkets/hypermarkets',
 'BusinessTypeID': 7840,
 'ChangesByServerID': 0,
 'Distance': 4646.946071297699,
 'FHRSID': 695223,
 'LocalAuthorityBusinessID': 'PI/000178842',
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE18 1JQ',
 'RatingDate': '2019-11-13T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('646bfa7c98a5457bc1c3b6e3'),
 'geocode': {'latitude': Decimal128('51.4871482849121'),
             'longitude': Decimal128('0.0924199968576431')},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695223',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 5}}

In [68]:
# Convert the result to a Pandas DataFrame
df3= pd.DataFrame(establishments.find(query3, {'BusinessName':1,'AddressLine1':1, 'AddressLine4':1,"geocode.latitude": 1, "geocode.longitude": 1, "scores": 1}))
# Display the number of rows in the DataFrame
print (f"There are {len(df3)} rows in this Data Frame.")
# Display the first 10 rows of the DataFrame
df3.head(10)

There are 87 rows in this Data Frame.

,_id,BusinessName,AddressLine1,AddressLine4,scores,geocode
0,646bfa7c98a5457bc1c3b6bc,TIWA N TIWA African Restaurant Ltd,152 Plumstead High Street,Greenwich,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.0927429, 'latitude': 51.4870351}"
1,646bfa7c98a5457bc1c3b6e3,Iceland,144 - 146 Plumstead High Street,Greenwich,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.0924199968576431, 'latitude': ..."
2,646bfa7c98a5457bc1c3b6f3,Howe and Co Fish and Chips - Van 17,Restaurant And Premises 107A Plumstead High St...,Greenwich,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.0925370007753372, 'latitude': ..."
3,646bfa7c98a5457bc1c3b710,Volunteer,130 - 132 Plumstead High Street,Greenwich,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.09208, 'latitude': 51.4873437}"
4,646bfa7c98a5457bc1c3b728,Plumstead Manor Nursery,Plumstead Manor School Old Mill Road,Greenwich,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.0859939977526665, 'latitude': ..."
5,646bfa7c98a5457bc1c3b72b,Atlantic Fish Bar,35 Lakedale Road,Greenwich,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.0912164, 'latitude': 51.4867296}"
6,646bfa7c98a5457bc1c3b72d,Lumbini Grocery Ltd T/A Al-Iman,17 Lakedale Road,Greenwich,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.0916256, 'latitude': 51.4871632}"
7,646bfa7c98a5457bc1c3b74b,Greggs,6 Lakedale Road,Greenwich,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.0912820026278496, 'latitude': ..."
8,646bfa7c98a5457bc1c3b74c,Tesco,18 Lakedale Road,Greenwich,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.0912820026278496, 'latitude': ..."
9,646bfa7c98a5457bc1c3b773,Dosa & Sambal Express,107A Plumstead High Street,Greenwich,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.091566, 'latitude': 51.4877576}"

In [48]:
# Convert result to Pandas DataFrame - full dataframe 
pd.DataFrame(establishments.find(query3).sort(sort).limit(10))

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,646bfa7c98a5457bc1c3b710,694609,0,PI/000116619,Volunteer,Pub/bar/nightclub,7843,130 - 132 Plumstead High Street,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.09208, 'latitude': 51.4873437}",,4646.965635,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
1,646bfa7c98a5457bc1c3b728,695241,0,PI/000179088,Plumstead Manor Nursery,Caring Premises,5,Plumstead Manor School Old Mill Road,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0859939977526665, 'latitude': ...",,4646.974010,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
2,646bfa7c98a5457bc1c3b72b,694478,0,PI/000086506,Atlantic Fish Bar,Takeaway/sandwich shop,7844,35 Lakedale Road,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0912164, 'latitude': 51.4867296}",,4646.974612,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
3,646bfa7c98a5457bc1c3b6e3,695223,0,PI/000178842,Iceland,Retailers - supermarkets/hypermarkets,7840,144 - 146 Plumstead High Street,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0924199968576431, 'latitude': ...",,4646.946071,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
4,646bfa7c98a5457bc1c3b6f3,1380578,0,14425,Howe and Co Fish and Chips - Van 17,Mobile caterer,7846,Restaurant And Premises 107A Plumstead High St...,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0925370007753372, 'latitude': ...",,4646.955931,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [49]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match_query = {'$match': {'scores.Hygiene': 0}}

# 2. Groups the matches by Local Authority and counts how many
group_query = {'$group': {'_id': '$LocalAuthorityName', 
                          'count': {'$sum': 1}
                         }
              }
# 3. Sorts the matches from highest to lowest
sort_query = {'$sort': {'count': -1}}

#Create pipeline 
pipeline = [match_query, group_query, sort_query]
results = list(establishments.aggregate(pipeline))

# Print the number of documents in the result
print(f"There are {len(results)} documents in the result.")

# Print the first 10 results
pprint(results[0:10])

There are 55 documents in the result.
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [50]:
# Convert the result to a Pandas DataFrame
agg_df = pd.json_normalize(results)

# Display the number of rows in the DataFrame
print(f"There are {len(agg_df)} rows in the DataFrame.")

# Display the first 10 rows of the DataFrame
agg_df.head(10)

There are 55 rows in the DataFrame.

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542

In [ ]:
#Thank you for taking time to assess this work. I look forward to your feedback.